# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PedidoW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pedido(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -20, 841, 661))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.506, y2:1, stop:0 rgba(0, 142, 202, 255), stop:0.846591 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 331, 71))
        self.label_2.setStyleSheet("font: 20pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.SelectorRestaurante = QtWidgets.QComboBox(self.centralwidget)
        self.SelectorRestaurante.setGeometry(QtCore.QRect(450, 70, 261, 31))
        self.SelectorRestaurante.setObjectName("SelectorRestaurante")
        self.SelectorRestaurante.addItem("")
        self.SelectorRestaurante.addItem("")
        self.SelectorRestaurante.addItem("")
        self.SelectorRestaurante.addItem("")
        self.SelectorRestaurante.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 331, 71))
        self.label_3.setStyleSheet("font: 20pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 200, 371, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Tarta = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Tarta.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.Tarta.setObjectName("Tarta")
        self.gridLayout.addWidget(self.Tarta, 4, 0, 1, 1)
        self.Filete = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Filete.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.Filete.setObjectName("Filete")
        self.gridLayout.addWidget(self.Filete, 1, 0, 1, 1)
        self.Hamburguesa = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Hamburguesa.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.Hamburguesa.setObjectName("Hamburguesa")
        self.gridLayout.addWidget(self.Hamburguesa, 3, 0, 1, 1)
        self.Lentejas = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Lentejas.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.Lentejas.setObjectName("Lentejas")
        self.gridLayout.addWidget(self.Lentejas, 2, 0, 1, 1)
        self.Pasta = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Pasta.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.Pasta.setObjectName("Pasta")
        self.gridLayout.addWidget(self.Pasta, 0, 0, 1, 1)
        self.EnviarPedido = QtWidgets.QPushButton(self.centralwidget)
        self.EnviarPedido.setGeometry(QtCore.QRect(480, 250, 241, 131))
        self.EnviarPedido.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EnviarPedido.setStyleSheet("font: 26pt \"Segoe UI\";")
        self.EnviarPedido.setObjectName("EnviarPedido")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Selecciona el Restaurante"))
        self.SelectorRestaurante.setItemText(0, _translate("MainWindow", "Selecciona restaurante"))
        self.SelectorRestaurante.setItemText(1, _translate("MainWindow", "Restaurante1"))
        self.SelectorRestaurante.setItemText(2, _translate("MainWindow", "Restaurante2"))
        self.SelectorRestaurante.setItemText(3, _translate("MainWindow", "Restaurante3"))
        self.SelectorRestaurante.setItemText(4, _translate("MainWindow", "Restaurante4"))
        self.label_3.setText(_translate("MainWindow", "Selecciona el Pedido"))
        self.Tarta.setText(_translate("MainWindow", "Tarta de queso"))
        self.Filete.setText(_translate("MainWindow", "Filete de ternera"))
        self.Hamburguesa.setText(_translate("MainWindow", "Hamburguesa traducional"))
        self.Lentejas.setText(_translate("MainWindow", "Lentejas de la abuela"))
        self.Pasta.setText(_translate("MainWindow", "Pasta a la carbonara"))
        self.EnviarPedido.setText(_translate("MainWindow", "Enviar pedido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Pedido()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
