# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeleccionRestauranteW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeleccionRestaurante(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -20, 841, 661))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.506, y2:1, stop:0 rgba(0, 142, 202, 255), stop:0.846591 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 90, 371, 71))
        self.label_2.setStyleSheet("font: 20pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 10, 231, 41))
        self.label_6.setStyleSheet("\n"
"font: 20pt \"Wide Latin\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 801, 51))
        self.label_7.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(42, 170, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.Restaurante1 = QtWidgets.QPushButton(self.centralwidget)
        self.Restaurante1.setGeometry(QtCore.QRect(20, 210, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Restaurante1.setFont(font)
        self.Restaurante1.setObjectName("Restaurante1")
        self.Restaurante2 = QtWidgets.QPushButton(self.centralwidget)
        self.Restaurante2.setGeometry(QtCore.QRect(220, 210, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Restaurante2.setFont(font)
        self.Restaurante2.setObjectName("Restaurante2")
        self.Restaurante3 = QtWidgets.QPushButton(self.centralwidget)
        self.Restaurante3.setGeometry(QtCore.QRect(420, 210, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Restaurante3.setFont(font)
        self.Restaurante3.setObjectName("Restaurante3")
        self.Restaurante4 = QtWidgets.QPushButton(self.centralwidget)
        self.Restaurante4.setGeometry(QtCore.QRect(610, 210, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Restaurante4.setFont(font)
        self.Restaurante4.setObjectName("Restaurante4")
        self.label.raise_()
        self.label_7.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.Restaurante1.raise_()
        self.Restaurante2.raise_()
        self.Restaurante3.raise_()
        self.Restaurante4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Selecciona el Restaurante"))
        self.label_6.setText(_translate("MainWindow", "GLOVO"))
        self.Restaurante1.setText(_translate("MainWindow", "Restaurante 1"))
        self.Restaurante2.setText(_translate("MainWindow", "Restaurante 2"))
        self.Restaurante3.setText(_translate("MainWindow", "Restaurante 3"))
        self.Restaurante4.setText(_translate("MainWindow", "Restaurante 4"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SeleccionRestaurante()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

